# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 02:01
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about1',
            field=wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('content', wagtail.wagtailcore.blocks.RichTextBlock()))),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about2',
            field=wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('content', wagtail.wagtailcore.blocks.RichTextBlock()))),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about3',
            field=wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('content', wagtail.wagtailcore.blocks.RichTextBlock()))),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about4',
            field=wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('content', wagtail.wagtailcore.blocks.RichTextBlock()))),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about5',
            field=wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('content', wagtail.wagtailcore.blocks.RichTextBlock()))),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about6',
            field=wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('content', wagtail.wagtailcore.blocks.RichTextBlock()))),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sh1',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sh2',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sh3',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
