# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171114_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='modt',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nyan',
            field=models.CharField(default='', max_length=16),
        ),
    ]
