# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 11:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171119_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='article',
            field=wagtail.wagtailcore.fields.StreamField((('aabout', wagtail.wagtailcore.blocks.StructBlock((('about_pages', wagtail.wagtailcore.blocks.StreamBlock((('about', wagtail.wagtailcore.blocks.StructBlock((('blink', wagtail.wagtailcore.blocks.CharBlock(blank=True, classname='full')), ('use_image', wagtail.wagtailcore.blocks.BooleanBlock(classname='full', default=False, help_text='Use picture instead of blink', required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(classname='full', required=False)), ('boxes', wagtail.wagtailcore.blocks.StreamBlock((('title', wagtail.wagtailcore.blocks.CharBlock(blank=True, classname='full title', icon='title')), ('content', wagtail.wagtailcore.blocks.RichTextBlock(blank=True, classname='full')))))), icon='doc-full')),), icon='cogs')),), icon='radio-empty')), ('amotd', wagtail.wagtailcore.blocks.StructBlock((('modt', wagtail.wagtailcore.blocks.CharBlock(classname='full', default="Sky's The Limit", max_length=16)),), icon='pilcrow')), ('asharingan', wagtail.wagtailcore.blocks.StructBlock((('sharingan', wagtail.wagtailcore.blocks.StructBlock((('sharingan_1', wagtail.wagtailcore.blocks.RichTextBlock(classname='full', default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')), ('sharingan_2', wagtail.wagtailcore.blocks.RichTextBlock(classname='full', default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')), ('sharingan_3', wagtail.wagtailcore.blocks.RichTextBlock(classname='full', default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')), ('nyan_titel', wagtail.wagtailcore.blocks.CharBlock(classname='full', default='The Team', max_length=16)), ('show_team', wagtail.wagtailcore.blocks.BooleanBlock(classname='full', default=False, help_text='Whether team block will be shown on page', required=False)), ('team', wagtail.wagtailcore.blocks.StreamBlock((('member', wagtail.wagtailcore.blocks.StructBlock((('pic', wagtail.wagtailimages.blocks.ImageChooserBlock(blank=True, classname='full')), ('name', wagtail.wagtailcore.blocks.CharBlock(blank=True, classname='full', default='', max_length=16)), ('description', wagtail.wagtailcore.blocks.CharBlock(classname='full', default='', max_length=128))), icon='user')),), required=False))))),), icon='view')), ('aspaceship', wagtail.wagtailcore.blocks.StructBlock((), icon='pick')), ('agallery', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(blank=True, classname='full')), ('gallery', wagtail.wagtailcore.blocks.StreamBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(blank=True, classname='full')),)))), icon='grip')), ('acode', wagtail.wagtailcore.blocks.StructBlock((('code', wagtail.wagtailcore.blocks.RawHTMLBlock(blank=True, classname='full')),), icon='code'))), blank=True),
        ),
    ]
